apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: prod-alago
- apiVersion: v1
  data:
    password: YWRtaW4xMjM=
    username: YWRtaW4=
  kind: Secret
  metadata:
    annotations:
      tekton.dev/docker-0: https://10.10.103.100:8123
    name: nexus-credentials
    namespace: prod-alago
  type: kubernetes.io/basic-auth
- apiVersion: v1
  data:
    known_hosts: MTAuMTAuMTAzLjEwMCBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUUNxNE84K1E0UHZmaHRJZFBwNEhpK3krOWF4YWFmOFlsQ0ZWZVN3Ym5Ra2ZaVXFjZHV5N2xCdCsySDk2UjluY2MzUFpIVGQ0aFFsVVhtR0JIYjg4TzMzMlE2R2M5d2dHVzkvWE5RVXA2MWk5N2kxc0tkTEZ0U2VEUW9aUjFKU2R2NStZT2dIazhSYnZ0Q081cDRmRkJIcVNBd1FVbFpOVXZ1TTdYOC9qTElJaGw1N0V4eFVQQkNYNTduV0xxOG1Xa0c3cktmRjU2cWFUK3FER0hpTzhGNDB6aksvRG9pSnJRRTI1Y0RodHlzbkpFRGI4TG1xc09UMEJIVnVPLzRYck1XTWVpUjMxREhOV1NTY2plS0UxR2hscTJURDJNa3JiVkd6VEZoV015UUhiSTZ0ZWVBZTVqV3ZHeGpKTVVkL05uWnhtVEZ5b0JoVzNnRUFXOFErN0Z4OQoxMC4xMC4xMDMuMTAwIGVjZHNhLXNoYTItbmlzdHAyNTYgQUFBQUUyVmpaSE5oTFhOb1lUSXRibWx6ZEhBeU5UWUFBQUFJYm1semRIQXlOVFlBQUFCQkJNR1R4TEg3THIzQzYvQTFuNmlUaDNDL1pXNFhyR0d4cTh1K0Jxc0k0dk9oSnRCWXdoOGNZY0xVaEVHemR0R1IwNXAvbkR3d0VYdENKK0hZallxVllTRT0KMTAuMTAuMTAzLjEwMCBzc2gtZWQyNTUxOSBBQUFBQzNOemFDMWxaREkxTlRFNUFBQUFJTFVXUGVWZGovWGMyQjlacUd3L1VaYkVBaks1bHZKWSttdDlxMklFemEwcQo=
    ssh-privatekey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUF6UUp0UDBvY3NiS0dNUTlMV1NUZ2tuQWgrWmlrdDNWblljOWFFbDZZTWpiYUV1WUREc292Cnp4cDdBR21MTGZxcXJTeEF5ZmliQzcxalBqbmcrYUZTLy9jVDBOU3F0VWZ3ZlYxL1IwZkVrRU41aEN1YXo2Qk5mRlp5SGYKby95SWZjaDVpTStCQ2M4ZlZhaEFVZUhKTlpQOHoway9iakN2UzFkQUJyRmFvS0JucFJZMFN3TDR3eWJLQkhOMXJqYmdoaQpGMWtXMVhnMUtDclkvSThJTU9Bak95Vm1FbU5EQlFkOTUrKzBRbXRwSTJZczY5R1diYzVsRWJMSXBHV0ZnT3QrbWdrZFc2CkNBS2t3TjllY1BZKzhLNk1paTR4WDJpNm1pM25pZmM1LytmekMyTHA4cFgzSlBwNVZSdHBVSmtNM1VUc3k5R05UYTBaOEEKbWxmSXVFazdSUjYxNnpHeE9tWXViSTg2ZjlRMUN1ZW5uTUpZK3Q5N1RKNTkzeTlLRXhEWkZPUDJ3SDE0Tk5YVUtKRnJTMwpObHZHa25GSk11aWZ2bXFJM2ZiWkc0TVI2c0x0ZUwrUE9PTEZ1SHROZENjQ3IxcnFsTWIxTHZaTDVDWmhXcEk5d0oxT3FiCnNFOXVqNlVkcUV0WVY5aW1ZcXlmeWx0b3UzbFhjcFlZWTJNOGhzWi9BQUFGa0FZNVYzVUdPVmQxQUFBQUIzTnphQzF5YzIKRUFBQUdCQU0wQ2JUOUtITEd5aGpFUFMxa2s0Skp3SWZtWXBMZDFaMkhQV2hKZW1ESTIyaExtQXc3S0w4OGFld0JwaXkzNgpxcTBzUU1uNG13dTlZejQ1NFBtaFV2LzNFOURVcXJWSDhIMWRmMGRIeEpCRGVZUXJtcytnVFh4V2NoMzZQOGlIM0llWWpQCmdRblBIMVdvUUZIaHlUV1QvTTlKUDI0d3IwdFhRQWF4V3FDZ1o2VVdORXNDK01NbXlnUnpkYTQyNElZaGRaRnRWNE5TZ3EKMlB5UENERGdJenNsWmhKalF3VUhmZWZ2dEVKcmFTTm1MT3ZSbG0zT1pSR3l5S1JsaFlEcmZwb0pIVnVnZ0NwTURmWG5EMgpQdkN1aklvdU1WOW91cG90NTRuM09mL244d3RpNmZLVjl5VDZlVlViYVZDWkROMUU3TXZSalUydEdmQUpwWHlMaEpPMFVlCnRlc3hzVHBtTG15UE9uL1VOUXJucDV6Q1dQcmZlMHllZmQ4dlNoTVEyUlRqOXNCOWVEVFYxQ2lSYTB0elpieHBKeFNUTG8Kbjc1cWlOMzIyUnVERWVyQzdYaS9qemppeGJoN1RYUW5BcTlhNnBURzlTNzJTK1FtWVZxU1BjQ2RUcW03QlBibytsSGFoTApXRmZZcG1Lc244cGJhTHQ1VjNLV0dHTmpQSWJHZndBQUFBTUJBQUVBQUFHQVVlYTBTbUtMVUJwb0xkVlVYc3F5eFEzekpNCm5zbERaZEZPQkh0YXNBMXA2L1JHbUxzeTduSnJBSGo4U2FpOFhteGNRMkpmb2h4dkRrWXdtd2JVb2I1SktLNGhUMEZmUWwKaVkvK3R6VmV1OXVaQWtxQlVJMVVKMlpKdE53eSt5UDc0RmY3aVdicHJHZyt2eHRrU2pvN241ZDc1bGp0bjRUZnNQWXgwYgpmYXhYZThhQklhNlFQemFSNG5GV0JFRjhOVm5NcEVxd2VaQlBFSk91elJjdVU0YmZxazZwZXBRS3NiaTd0aG9sOVM0NGVBClRyMnVnVFBCZ082UjVjdUJLRjNyd08vMnlpVkxmbE50RytkeXR3SnV3bXdSZ2RNelJDSHk1RGVmV3pnU0wyRHYzaTZacUkKaVFYcHdMZU9CNUZraDlCMThRTHVnaWxpY1VqeTh6a1JvbW1ydmgwRHdBTWpMY1JyemxDN2UwaXhnQlpYRWdMZkN4emk1UwpvaXpZTVAvK0xPaVd5cmJxQkdhdUNEQmhPMExOQ3ZxdHk0NThIQ2tpbWlmbnkvc3R0VWVMaWJJVi9wZkIxT2psU1lieDYwCmFmY1BUVHFxaGxkcGVkVnBMTDg1RC8rNVpPWFVLSnphSVk2ZEFlVGpCWEJGc2ZYZHhPcUpubkRMQlpyT2JWczR6QkFBQUEKd0J6eURYTXF3eTRRaFlRRzg1VHcxb1Z1Rll6WUFZS2h3clRZNFloOHZnK3NIbkVHenpUU041YmlFWDZwMDNtVVkwS2I0cwpsbU1jdGs1Q1EyRXNsQU40bjVMRlZmZm94Q0Z2RFdjSUhLeGZlZTJlaG01NlBvWWIxeThEeklibmE2eGpsOHpUbFN3R2ZBCjNSQXBLcTh4V3hqeFIxd0kvOE1oVXBmQzVncDBvaEtwLzBVVnNXTG9NRUloUmN2R09xRnVsbVZXajVHYjZQc2s5VDYyc3gKS3Q5QVkyNUlRUDNlQUtyM2hhK1VDa09SUDhXak9JRWpJSnJtcFRqRVRra25Tb3pnQUFBTUVBN0VTZjNuNFdIUHgxSFNUdwoya25va3lUMkdGZU0vRHpON2ZiV3NodlNYNDZqR0VEWUgwaG5tWGN0eWhJa2NZWXVxaWZxdXBxZG5PQmdlekhrTGdUaUhVCis4OUNNS3ljbXZMbnZmalNQenk1dzVNVTRNekQ3dmpPVmplNjd0SWpjR0w3cCtBQVNZTFprdmVyeDI5ZE1rR0dxUUVCVmkKNWp6VllvVW1KeXdKcXJMZnZ0RHFFSGY2cDlQS2N1cmxpbnRPNkZGc28yU3lsc1ZlbU9mZGVRT25uL2Vkais3bENsWWVqTApGTytiajh6K1hQL2l4aG1FNVVHQ2JqNXh1ZEFpN3ZBQUFBd1FEZUlYK1poeS9XMXhBZkxBRitUNjNmcDBZYmhUTzdENW5oClo3aVRTdnFFVUNBS3EzSU50V0x1RC9ZN3dCcVVUYnhLS1BaS3EwRTdUSWc5N2pzTTRXR1RRc0U3SWFkZ2FMcXM0bjBHOE0Ka0RRUS9wN3dMMHl3L1dVKzlYb3VuMDI2R0hTZHUvaVZCbWdRczlIRUpZTlAzeEg3Q04rNWxITXF2eHZzai9wOXc5dmF0TQpjRkFlNkdybEFuS1hQY2NLdUFPZ3hsRXZHSFRjUExWdkNhdnM1T2RMbDI5SFE1V3p1KzgxeTc3TXd3NUI1TjhBaVdodnJ0Ckh1VVg4c3lER3c0WEVBQUFBVmNtRnNkbUZ5WlhwQWNtRnNkbUZ5WlhvdGJXRmpBUUlEQkFVRwotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
  kind: Secret
  metadata:
    annotations:
      tekton.dev/git-0: 10.10.103.100
    name: repository-credentials
    namespace: prod-alago
  type: kubernetes.io/ssh-auth
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pipeline
    namespace: prod-alago
  secrets:
  - name: repository-credentials
  - name: nexus-credentials
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: workspace-pvc
    namespace: prod-alago
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
kind: List
metadata: {}
