apiVersion: template.openshift.io/v1
kind: Template 
metadata:
  name: dev-app-template
  namespace: openshift
  annotations:
    description: Template para crear apps de desarrollo
parameters:
  - name: APP_NAME
    required: true
  - name: BASE_PROJECT
    required: true
  - name: NAMESPACE
    value: openshift-gitops
  - name: GIT_KUSTOMIZE
    required: true
objects:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: dev-${APP_NAME}-app
    namespace: ${NAMESPACE}
  spec:
    destination:
      namespace: dev-${BASE_PROJECT}
      server: 'https://kubernetes.default.svc'
    ignoreDifferences:
      - group: apps
        jsonPointers:
          - /spec/template/spec/containers/0/image
        kind: Deployment
    project: dev-${BASE_PROJECT}
    source:
      path: overlays/dev
      repoURL: '${GIT_KUSTOMIZE}'
      targetRevision: main
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
        - Validate=false
        - ApplyOutOfSyncOnly=true