apiVersion: v1
kind: Secret
metadata:
  name: repository-gitops
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: GitOps
  url: https://github.com/agustinlago/devops.git
  type: git
  insecure: 'true'
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: repository-cicd
#  namespace: openshift-gitops
#  labels:
#    argocd.argoproj.io/secret-type: repository
#stringData:
#  name: CICD
#  url: https://github.com/agustinlago/devops.git
#  type: git
#  insecure: 'true'