apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      argocd.argoproj.io/secret-type: repository
    name: repository-test
  stringData:
    insecure: "true"
    name: test
    type: git
    url: https://github.com/agustinlago/manifests-test.git
kind: List
metadata: {}
