apiVersion: template.openshift.io/v1
kind: Template 
metadata:
  name: prod-app-template
  namespace: openshift
  annotations:
    description: Template para crear apps de produccion
parameters:
  - name: APP_NAME
    required: true
  - name: BASE_PROJECT
    required: true
  - name: NAMESPACE
    value: openshift-gitops
objects:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: prod-${APP_NAME}-app
    namespace: ${NAMESPACE}
  spec:
    destination:
      namespace: prod-${BASE_PROJECT}
      server: 'https://kubernetes.default.svc'
    ignoreDifferences:
      - group: '*'
        jsonPointers:
          - /spec/tls
        kind: Route
    project: prod-${BASE_PROJECT}
    source:
      path: overlays/prod
      repoURL: 'ssh://git@10.10.103.100/DevOps/manifests/${BASE_PROJECT}/${APP_NAME}.git'
      targetRevision: master
    syncPolicy: {}