apiVersion: v1
items:
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: test-java-ci-pipeline
  spec:
    params:
    - default: test
      description: The application deployment name
      name: APP_NAME
      type: string
    - default: ssh://git@10.10.103.100/alago/test.git
      description: The application git repository url
      name: SOURCE_GIT_URL
      type: string
    - default: develop
      description: The application git repository revision
      name: SOURCE_GIT_REVISION
      type: string
    - default: test
      description: The subdirectory in the git repository
      name: SOURCE_GIT_CONTEXT_DIR
      type: string
    - default: ""
      description: Maven mirror for Maven Builds
      name: MAVEN_MIRROR_URL
      type: string
    - default: dev-alago
      description: Namespace where the buildconfig is located
      name: NAMESPACE
      type: string
    tasks:
    - name: git-clone
      params:
      - name: url
        value: $(params.SOURCE_GIT_URL)
      - name: revision
        value: $(params.SOURCE_GIT_REVISION)
      - name: subdirectory
        value: $(params.SOURCE_GIT_CONTEXT_DIR)
      - name: deleteExisting
        value: "true"
      retries: 2
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: app-source
    - name: maven-build
      params:
      - name: MAVEN_IMAGE
        value: image-registry.openshift-image-registry.svc:5000/openshift/openjdk-11-rhel8:1.0
      - name: CONTEXT_DIR
        value: ./$(params.SOURCE_GIT_CONTEXT_DIR)
      - name: GOALS
        value:
        - -DskipTests
        - clean
        - compile
        - package
      - name: MAVEN_MIRROR_URL
        value: $(params.MAVEN_MIRROR_URL)
      retries: 3
      runAfter:
      - git-clone
      taskRef:
        kind: ClusterTask
        name: maven-custom
      workspaces:
      - name: source
        workspace: app-source
      - name: maven-settings
        workspace: maven-settings
    - name: build-image
      params:
      - name: FROM_DIRECTORY
        value: ./source/$(params.SOURCE_GIT_CONTEXT_DIR)/target
      - name: NAMESPACE
        value: $(params.NAMESPACE)
      - name: BUILDCONFIG
        value: $(params.APP_NAME)
      retries: 3
      runAfter:
      - maven-build
      taskRef:
        kind: ClusterTask
        name: s2i-binary-custom
      workspaces:
      - name: source
        workspace: app-source
    workspaces:
    - name: app-source
    - name: maven-settings
kind: List
metadata: {}
