apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: uat-test-app
    namespace: openshift-gitops
  spec:
    destination:
      namespace: uat-alago
      server: https://kubernetes.default.svc
    ignoreDifferences:
    - group: '*'
      jsonPointers:
      - /spec/tls
      kind: Route
    project: uat-alago
    source:
      path: overlays/uat
      repoURL: https://github.com/agustinlago/manifests-test.git
      targetRevision: main
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
kind: List
metadata: {}
