apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repositories
  namespace: openshift-gitops
spec:
  destination:
    namespace: 'openshift-gitops'
    server: 'https://kubernetes.default.svc'
  source:
    path: repositories
    repoURL: 'ssh://git@10.10.103.100/devops/gitops.git'
    targetRevision: master
    directory:
      recurse: true
  project: openshift-gitops
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true