apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repositories
  namespace: openshift-gitops
spec:
  destination:
    namespace: 'openshift-gitops'
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops/repositories
    repoURL: 'https://github.com/agustinlago/devops.git'
    targetRevision: main
    directory:
      recurse: true
  project: openshift-gitops
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true