apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "test:latest"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
spec:
  template:
    spec:
      containers:
      - name: test
        image: image-registry.openshift-image-registry.svc:5000/dev-alago/test:latest