apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: dev-test-app
    namespace: openshift-gitops
  spec:
    destination:
      namespace: dev-alago
      server: https://kubernetes.default.svc
    ignoreDifferences:
    - group: apps
      jsonPointers:
      - /spec/template/spec/containers/0/image
      kind: Deployment
    project: dev-alago
    source:
      path: overlays/dev
      plugin:
        name: argocd-vault-plugin-kustomize
      repoURL: https://github.com/agustinlago/manifests-test.git
      targetRevision: main
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
kind: List
metadata: {}
