apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: qa-test-app
    namespace: openshift-gitops
  spec:
    destination:
      namespace: qa-alago
      server: https://kubernetes.default.svc
    ignoreDifferences:
    - group: '*'
      jsonPointers:
      - /spec/tls
      kind: Route
    project: qa-alago
    source:
      path: manifests/alago/overlays/qa
      repoURL: https://github.com/agustinlago/devops.git
      targetRevision: main
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
kind: List
metadata: {}
