apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: prod-test-app
    namespace: openshift-gitops
  spec:
    destination:
      namespace: prod-alago
      server: https://kubernetes.default.svc
    ignoreDifferences:
    - group: '*'
      jsonPointers:
      - /spec/tls
      kind: Route
    project: prod-alago
    source:
      path: overlays/prod
      repoURL: ssh://git@10.10.103.100/DevOps/manifests/alago/test.git
      targetRevision: master
    syncPolicy: {}
kind: List
metadata: {}
