apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    name: alago
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: AppProject
    - group: argoproj.io
      kind: ApplicationSet
    - group: '*'
      kind: Secret
    - group: '*'
      kind: PersistentVolumeClaim
    - group: '*'
      kind: Pipeline
    - group: '*'
      kind: ServiceAccount
    
    destinations:
    - namespace: openshift-gitops
      server: https://kubernetes.default.svc
    - namespace: dev-alago
      server: https://kubernetes.default.svc
    - namespace: qa-alago
      server: https://kubernetes.default.svc
    - namespace: uat-alago
      server: https://kubernetes.default.svc
    namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
    sourceRepos:
    - '*'
- apiVersion: argoproj.io/v1alpha1
  kind: ApplicationSet
  metadata:
    name: alago-set
  spec:
    generators:
    - list:
        elements:
        - env: dev
          project: alago
        - env: qa
          project: alago
        - env: uat
          project: alago
    template:
      metadata:
        finalizers:
        - resources-finalizer.argocd.argoproj.io
        name: '{{env}}-{{project}}'
        namespace: openshift-gitops
      spec:
        destination:
          namespace: '{{env}}-{{project}}'
          server: https://kubernetes.default.svc
        project: '{{project}}'
        source:
          directory:
            recurse: true
          path: ocp-bajos/proyectos/{{project}}/{{env}}
          repoURL: ssh://git@10.10.103.100/devops/gitops.git
          targetRevision: master
        syncPolicy:
          automated:
            selfHeal: true
          syncOptions:
          - Validate=false
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    name: dev-alago
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: '*'
      kind: Secret
    - group: '*'
      kind: PersistentVolumeClaim
    - group: '*'
      kind: Pipeline
    - group: '*'
      kind: ServiceAccount
    
    destinations:
    - namespace: dev-alago
      server: https://kubernetes.default.svc
    namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
    sourceRepos:
    - '*'
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    name: qa-alago
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: '*'
      kind: Secret
    - group: '*'
      kind: PersistentVolumeClaim
    - group: '*'
      kind: Pipeline
    - group: '*'
      kind: ServiceAccount
    
    destinations:
    - namespace: qa-alago
      server: https://kubernetes.default.svc
    namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
    sourceRepos:
    - '*'
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    name: uat-alago
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: '*'
      kind: Secret
    - group: '*'
      kind: PersistentVolumeClaim
    - group: '*'
      kind: Pipeline
    - group: '*'
      kind: ServiceAccount
    
    destinations:
    - namespace: uat-alago
      server: https://kubernetes.default.svc
    namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
    sourceRepos:
    - '*'
kind: List
metadata: {}
