apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: permisos-redhat-staff
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'openshift-gitops'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'ocp-bajos/permisos/redhat-staff'
    repoURL: 'ssh://git@10.10.103.100/devops/gitops.git'
    targetRevision: master
  project: 'openshift-gitops'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true