apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: dev-alago
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: workspace-pvc
    namespace: dev-alago
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: pipeline-puller
    namespace: qa-alago
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: pipeline-puller
  subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: uat-alago
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    name: dev-alago
    namespace: openshift-gitops
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: '*'
      kind: Secret
    - group: '*'
      kind: PersistentVolumeClaim
    - group: '*'
      kind: Pipeline
    - group: '*'
      kind: ServiceAccount
    destinations:
    - namespace: dev-alago
      server: https://kubernetes.default.svc
    namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
    roles: null
    sourceRepos:
    - '*'
kind: List
metadata: {}
