apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: dev-alago
- apiVersion: v1
  data:
    password: YWRtaW4xMjM=
    username: YWRtaW4=
  kind: Secret
  metadata:
    annotations:
      tekton.dev/docker-0: https://10.10.103.100:8123
    name: nexus-credentials
    namespace: dev-alago
  type: kubernetes.io/basic-auth
- apiVersion: v1
  data:
    known_hosts: MTAuMTAuMTAzLjEwMCBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUUNxNE84K1E0UHZmaHRJZFBwNEhpK3krOWF4YWFmOFlsQ0ZWZVN3Ym5Ra2ZaVXFjZHV5N2xCdCsySDk2UjluY2MzUFpIVGQ0aFFsVVhtR0JIYjg4TzMzMlE2R2M5d2dHVzkvWE5RVXA2MWk5N2kxc0tkTEZ0U2VEUW9aUjFKU2R2NStZT2dIazhSYnZ0Q081cDRmRkJIcVNBd1FVbFpOVXZ1TTdYOC9qTElJaGw1N0V4eFVQQkNYNTduV0xxOG1Xa0c3cktmRjU2cWFUK3FER0hpTzhGNDB6aksvRG9pSnJRRTI1Y0RodHlzbkpFRGI4TG1xc09UMEJIVnVPLzRYck1XTWVpUjMxREhOV1NTY2plS0UxR2hscTJURDJNa3JiVkd6VEZoV015UUhiSTZ0ZWVBZTVqV3ZHeGpKTVVkL05uWnhtVEZ5b0JoVzNnRUFXOFErN0Z4OQoxMC4xMC4xMDMuMTAwIGVjZHNhLXNoYTItbmlzdHAyNTYgQUFBQUUyVmpaSE5oTFhOb1lUSXRibWx6ZEhBeU5UWUFBQUFJYm1semRIQXlOVFlBQUFCQkJNR1R4TEg3THIzQzYvQTFuNmlUaDNDL1pXNFhyR0d4cTh1K0Jxc0k0dk9oSnRCWXdoOGNZY0xVaEVHemR0R1IwNXAvbkR3d0VYdENKK0hZallxVllTRT0KMTAuMTAuMTAzLjEwMCBzc2gtZWQyNTUxOSBBQUFBQzNOemFDMWxaREkxTlRFNUFBQUFJTFVXUGVWZGovWGMyQjlacUd3L1VaYkVBaks1bHZKWSttdDlxMklFemEwcQo=
    ssh-privatekey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDTncrR2Jqb25RaHVFQklkemJKbkRKUk9wRlkzbDB6aUprMHhmV1ZYQXNQZ0FBQUpoTjY4SnZUZXZDCmJ3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ053K0diam9uUWh1RUJJZHpiSm5ESlJPcEZZM2wwemlKazB4ZldWWEFzUGcKQUFBRUF5bCtGa2NnT3crWXhSNDlZTHN6N3FNcFlzZ2Zxc0Z3UGtGMGQ4Wkl2RnBJM0Q0WnVPaWRDRzRRRWgzTnNtY01sRQo2a1ZqZVhUT0ltVFRGOVpWY0N3K0FBQUFFV1JsZGkxdmNHVnVjMmhwWm5SQWIyTndBUUlEQkE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
  kind: Secret
  metadata:
    annotations:
      tekton.dev/git-0: 10.10.103.100
    name: repository-credentials
    namespace: dev-alago
  type: kubernetes.io/ssh-auth
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pipeline
    namespace: dev-alago
  secrets:
  - name: repository-credentials
  - name: nexus-credentials
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: workspace-pvc
    namespace: dev-alago
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
kind: List
metadata: {}
